#! /bin/bash -l
#$ -j y
#$ -m ea
#$ -l buyin

## --- Model Loop --- ##
#$ -l h_rt=120:00:00
#$ -l mem_per_core=4G
#$ -t 1-15
#$ -N MonthDiffPrior
#$ -o ../Output_Files/K_all/
module load R/3.6.0
Rscript Scripts/Run_Model_Loop.R

# Rscript ExploreScripts/restart_model.R



## --- Survival --- ##
# #$ -pe omp 1
# #$ -l h_rt=48:00:00
# #$ -N survival_nymph
# #$ -o ../Output_Files/Survival/
# module load R
# Rscript Models/Cary_Survival.R

## --- Mark Recapture --- ##
# #$ -pe omp 1
# #$ -l mem_per_core=16G
# #$ -l h_rt=120:00:00
# #$ -t 1-5
# #$ -N MR_henry
# #$ -o ../Output_Files/MR/
# module load R
# Rscript ExploreScripts/restart_model.R
# Rscript Models/MR_Recruit.R

## --- Testing --- ##
# #$ -l buyin
# #$ -pe omp 1
# #$ -l h_rt=24:00:00
# # #$ -t 1-5
# #$ -N mouse_out
# #$ -o ../Output_Files/Testing/
# module load R
# Rscript Mouse_out.R

